services:
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - /home/ubuntu/tracker_back/static:/app/static
      - /home/ubuntu/tracker_back/media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - telegram_bot

  celery:
    build: .
    restart: always
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    restart: always
    command: celery -A config beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: tracker
      POSTGRES_USER: bulbazavr
      POSTGRES_PASSWORD: 1

  redis:
    image: redis:latest
    restart: always

  telegram_bot:
    build: .
    command: python bot.py
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

volumes:
  .:
  postgres_data:
  static_volume:
  media_volume:
